export const GET_INVENTORY = 'GET_INVENTORY';
export const REQUEST_POSTS = 'REQUEST_POSTS';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';

export const GET_DASHBOARD_MEMBER_DATA = 'GET_DASHBOARD_MEMBER_DATA';
export const REQUEST_DASHBOARD_MEMBER_DATA = 'REQUEST_DASHBOARD_MEMBER_DATA';
export const RECEIVE_DASHBOARD_MEMBER_DATA = 'RECEIVE_DASHBOARD_MEMBER_DATA';


export const LOGIN = 'LOGIN';
